trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Install dependencies and build the React app
- script: |
    cd Client || exit 1  # Navigate to the client folder or exit if not found
    echo "Current directory contents before build:"
    ls -al  # List contents of current directory
    npm install  # Install React app dependencies
    npm run build  # Build the React app for production
    echo "Current directory contents after build:"
    ls -al  # List contents again after build
  displayName: 'npm install and build in client folder'


# Deploy to Azure Static Web App
- task: AzureStaticWebApp@0
  inputs:
    azure_static_web_apps_api_token: c4dd6bb70d50937f8ad7307d9e2ce42db0721d504755dba5fe7e58b281edc3b506-8e924fc7-e5dc-49fe-b18f-021521bf645701000230c54f2210  # Token from Azure DevOps secret
    app_location: "/Client"  # Path to your React app folder
    api_location: ""  # If you don't have an API, leave this blank
    output_location: "Client/build"  # Correct path to the React build folder
